module.exports = {
  printWidth: 80,
  tabWidth: 4,
  useTabs: false,
  semi: false,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  trailingComma: 'es5',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  proseWrap: 'preserve',
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  endOfLine: 'auto',
  plugins: ['prettier-plugin-scss'],
  scss: {
    singleQuote: true,
    trailingComma: 'es5',
  },
}
